FROM python:3.10-slim

WORKDIR /app

# Install Prefect
RUN pip install prefect
# Expose Prefect port
EXPOSE 4200

# Start Prefect server
CMD ["prefect", "server", "start", "--host", "0.0.0.0", "--port", "4200"]